services:
  node-dev:
    image: redefi-parachain:latest
    container_name: redefi-parachain
    expose:
      - 9944
    ports:
      - 127.0.0.1:9944:9944
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    command: cargo run --dev -linfo --rpc-cors=all --unsafe-rpc-external