# https://cryptousetech.atlassian.net/wiki/spaces/CI/pages/2586837012/Code+style+testing
# Nested workflow for checks related to formatting Rust code 

name: codestyle

# Triger: only call from main workflow(re-usable workflows)
on:
  workflow_call:
    inputs:
      relay-runtime-ref:
        type: string
        description: SHA commit from relay-runtime
  workflow_dispatch:            

jobs:
  rustfmt:
    runs-on: [ redefi-03 ]
    steps:
      - name: Clean Workspace
        uses: AutoModality/action-clean@v1.1.0      
      - name: Read .env file
        uses: xom9ikk/dotenv@v2          
      - name: Install toolchain version from .env
        uses: dtolnay/rust-toolchain@master
        with:
            toolchain: ${{ env.RUST_TOOLCHAIN }}
            targets: wasm32-unknown-unknown
            components: rustfmt, clippy
      - uses: actions/checkout@v3.1.0
        with:
          ref: ${{ github.head_ref }}

      - name: Checkout redefi-relay-runtime
        uses: actions/checkout@v3.1.0
        with:
          repository: 'ReDeFi-Blockchain/redefi-relay-runtime'
          path: 'redefi-relay-runtime'
          ref: 'main'

      - name: Run cargo fmt for redefi-relay-runtime
        working-directory: redefi-relay-runtime
        run: cargo fmt -- --check   # In that mode it returns only exit code.

      - name: Cargo fmt state for redefi-relay-runtime
        if: success()
        run: echo "Nothing to do. Command 'cargo fmt -- --check' returned exit code 0."

