name: relay-node-only-update

# Triger: only call from main workflow(re-usable workflows)
on:
  workflow_call:
    inputs:
      relay-node-version:
        type: string
        description: relay branch to build
        required: true
      relay-runtime-version:
        type: string
        description: relay runtime branch to build
        required: true
      parachain-version:
        type: string
        description: parachain branch to build
        required: true
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  node-only-update:
    runs-on: [ self-hosted ]
    timeout-minutes: 2880           # 48 hours for execution jobs.
    name: relay-node-only-update
    continue-on-error: true

    steps:
      - name: Skip if pull request is in Draft
        if: github.event.pull_request.draft == true
        run: exit 1

      - name: Clean Workspace
        if: always()
        uses: AutoModality/action-clean@v1.1.0

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4.1.7
        with:
          ref: ${{ github.head_ref }}  #Checking out head commit

      # # Prepare SHA  
      # - name: Prepare SHA
      #   uses: ./.github/actions/prepare

      - name: Read .env file
        uses: xom9ikk/dotenv@v2.3.0

      - name: Pull polkadot image from official repository
        run: |
          docker pull parity/polkadot:v1.7.0

      - name: Prepare redefi-relay-runtime container
        uses: ./.github/actions/buildContainer
        id: redefi-relay-runtime
        with:
          container: redefi-relay-runtime
          tag: latest
          context: .docker
          dockerfile: Dockerfile-relay-runtime
          args: |
            --build-arg REDEFI_RELAY_RUNTIME=${{ env.REDEFI_RELAY_RUNTIME_MAINNET_VERSION }}          

      - name: Copy runtime wasm file to host
        run: |
          docker run -v $PWD:/infra --rm --entrypoint cp ${{ steps.redefi-relay-runtime.outputs.name }} /redefi/redefi_runtime.compact.compressed.wasm /infra/
   
      - name: Prepare redefi-relay mainnet container
        uses: ./.github/actions/buildContainer
        id: redefi-relay-mainnet
        with:
          container: redefi-relay
          tag: mainnet
          context: .docker
          dockerfile: Dockerfile-relay
          args: |
            --build-arg REDEFI_RELAY=${{ env.REDEFI_RELAY_MAINNET_VERSION }}     

      - name: Prepare redefi-relay latest container
        uses: ./.github/actions/buildContainer
        id: redefi-relay-latest
        with:
          container: redefi-relay
          tag: latest
          context: .docker
          dockerfile: Dockerfile-relay
          args: |
            --build-arg REDEFI_RELAY=${{ inputs.relay-node-version }}     

      - name: Prepare redefi-parachain mainnet container
        uses: ./.github/actions/buildContainer
        id: redefi-parachain-mainnet
        with:
          container: redefi-parachain
          tag: mainnet
          context: .docker
          dockerfile: Dockerfile-parachain
          args: |
            --build-arg REDEFI_PARACHAIN=${{ env.REDEFI_PARACHAIN_MAINNET_VERSION }}     

      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - name: Install baedeker
        uses: UniqueNetwork/baedeker-action/setup@v1-no-debug-output
        with:
          useCache: false

      - name: Setup library
        run: mkdir -p .baedeker/vendor/ && git clone https://github.com/UniqueNetwork/baedeker-library .baedeker/vendor/baedeker-library

      - name: Start network
        uses: UniqueNetwork/baedeker-action@v1-no-debug-output
        if: success()
        id: bdk
        with:
          jpath: |
            .baedeker/vendor
          tla-str: |
            relay_spec=${{ env.RELAY_CHAIN_TYPE }}-local            
          inputs: |
            .baedeker/redefi.jsonnet
            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/polkadot':{dockerImage:'parity/polkadot:v1.7.0'}})
            ephemeral:snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/redefi-relay':{dockerImage:'${{ steps.redefi-relay-mainnet.outputs.name }}'}})
            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/redefi-collator':{dockerImage:'${{ steps.redefi-parachain-mainnet.outputs.name }}'}})

      - name: Ensure network is alive
        working-directory: ./tests
        id: alive1
        if: ${{ !cancelled() && steps.bdk.outcome == 'success' }}
        run: |
          yarn        
          ./scripts/wait_for_first_block.sh
        env:
          RPC_URL_MAIN: ${{ env.REDEFI_RELAY_REDEFI_PARACHAIN_HTTP_URL }}

      - name: Run test:setup before Node upgrade
        working-directory: ./tests
        id: test-setup1
        if: ${{ !cancelled() && steps.alive1.outcome == 'success' }}
        run: |
          echo "Ready to start test:setup"
          yarn test:setup 
        env:
          RPC_URL_MAIN: ${{ env.REDEFI_RELAY_HTTP_URL }}
          RPC_URL_SIBLING: ${{ env.REDEFI_RELAY_REDEFI_PARACHAIN_HTTP_URL }}
          CROSSCHAIN: ${{ env.CROSSCHAIN }}

      - name: Run test:regular before Node upgrade
        working-directory: ./tests
        if: ${{ !cancelled() && steps.test-setup1.outcome == 'success' }}
        run: |
          echo "Ready to start test:regular"
          yarn test:regular
        env:
          RPC_URL_MAIN: ${{ env.REDEFI_RELAY_HTTP_URL }}
          RPC_URL_SIBLING: ${{ env.REDEFI_RELAY_REDEFI_PARACHAIN_HTTP_URL }}
          CROSSCHAIN: ${{ env.CROSSCHAIN }}

      - name: Run test:serial before Node upgrade
        working-directory: ./tests
        if: ${{ !cancelled() && steps.test-setup1.outcome == 'success' }}
        run: |
          echo "Ready to start test:serial"
          yarn test:serial
        env:
          RPC_URL_MAIN: ${{ env.REDEFI_RELAY_HTTP_URL }}
          RPC_URL_SIBLING: ${{ env.REDEFI_RELAY_REDEFI_PARACHAIN_HTTP_URL }}
          CROSSCHAIN: ${{ env.CROSSCHAIN }}

      - name: Run test:smoke for parachain before upgrade
        working-directory: ./tests
        id: test-smoke1
        if: ${{ !cancelled() && steps.test-setup1.outcome == 'success' }}
        run: |
          echo "Ready to start test:smoke"
          yarn test:smoke
        env:
          RPC_URL_MAIN: ${{ env.REDEFI_RELAY_REDEFI_PARACHAIN_HTTP_URL }}
          RPC_URL_SIBLING: ${{ env.REDEFI_RELAY_HTTP_URL }}
          CROSSCHAIN: ${{ env.CROSSCHAIN }}

      - name: "Reconcile: only one old node"
        id: reconcile1
        if: ${{ !cancelled() && steps.alive1.outcome == 'success' }}        
        uses: UniqueNetwork/baedeker-action/reconcile@v1-no-debug-output
        with:
          baedeker: ${{ steps.bdk.outputs.baedeker }}
          # Chain should always be built with the mainnet spec, this we first set binary for all nodes expect one, then set mainnet binary for the last node, and then force chainspec to be still generated from mainnet
          inputs: |
            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/redefi-relay':{dockerImage:'${{ steps.redefi-relay-latest.outputs.name }}'}}, leave = 1, for_chain = false)
            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/redefi-relay':{dockerImage:'${{ steps.redefi-relay-mainnet.outputs.name }}'}}, for_chain = false)
            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/redefi-relay':{dockerImage:'${{ steps.redefi-relay-mainnet.outputs.name }}'}})

      - name: Ensure network is alive
        working-directory: ./tests
        id: alive2
        if: ${{ !cancelled() && steps.reconcile1.outcome == 'success' }}
        run: |
          ./scripts/wait_for_first_block.sh
        env:
          RPC_URL_MAIN: ${{ env.REDEFI_RELAY_REDEFI_PARACHAIN_HTTP_URL }}

      - name: "Reconcile: all nodes are updated"
        id: reconcile2
        if: ${{ !cancelled() && steps.alive2.outcome == 'success' }}
        uses: UniqueNetwork/baedeker-action/reconcile@v1-no-debug-output
        with:
          baedeker: ${{ steps.bdk.outputs.baedeker }}
          # Chain should always be built with the mainnet spec, this we first set binary for all nodes, and then force chainspec to be still generated from mainnet
          inputs: |
            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/redefi-relay':{dockerImage:'${{ steps.redefi-relay-latest.outputs.name }}'}}, for_chain = false)
            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/redefi-relay':{dockerImage:'${{ steps.redefi-relay-mainnet.outputs.name }}'}})

      - name: Ensure network is alive
        working-directory: ./tests
        if: ${{ !cancelled() && steps.reconcile2.outcome == 'success' }}
        id: alive3
        run: |
          ./scripts/wait_for_first_block.sh
        env:
          RPC_URL_MAIN: ${{ env.REDEFI_RELAY_REDEFI_PARACHAIN_HTTP_URL }}

      - name: Run test:setup after Node upgrade
        working-directory: ./tests
        id: test-setup2
        if: ${{ !cancelled() && steps.alive3.outcome == 'success' }}
        run: |
          echo "Ready to start test:setup"
          yarn test:setup 
        env:
          RPC_URL_MAIN: ${{ env.REDEFI_RELAY_HTTP_URL }}
          RPC_URL_SIBLING: ${{ env.REDEFI_RELAY_REDEFI_PARACHAIN_HTTP_URL }}
          CROSSCHAIN: ${{ env.CROSSCHAIN }}

      - name: Run test:regular after Node upgrade
        working-directory: ./tests
        if: ${{ !cancelled() && steps.test-setup2.outcome == 'success' }}
        run: |
          echo "Ready to start test:regular"
          yarn test:regular
        env:
          RPC_URL_MAIN: ${{ env.REDEFI_RELAY_HTTP_URL }}
          RPC_URL_SIBLING: ${{ env.REDEFI_RELAY_REDEFI_PARACHAIN_HTTP_URL }}
          CROSSCHAIN: ${{ env.CROSSCHAIN }}

      - name: Run test:serial after Node upgrade
        working-directory: ./tests
        if: ${{ !cancelled() && steps.test-setup2.outcome == 'success' }}
        run: |
          echo "Ready to start test:serial"
          yarn test:serial
        env:
          RPC_URL_MAIN: ${{ env.REDEFI_RELAY_HTTP_URL }}
          RPC_URL_SIBLING: ${{ env.REDEFI_RELAY_REDEFI_PARACHAIN_HTTP_URL }}
          CROSSCHAIN: ${{ env.CROSSCHAIN }}

      - name: Run test:smoke for parachain after upgrade
        working-directory: ./tests
        id: test-smoke2
        if: ${{ !cancelled() && steps.test-setup2.outcome == 'success' }}
        run: |
          echo "Ready to start test:smoke"
          yarn test:smoke
        env:
          RPC_URL_MAIN: ${{ env.REDEFI_RELAY_REDEFI_PARACHAIN_HTTP_URL }}
          RPC_URL_SIBLING: ${{ env.REDEFI_RELAY_HTTP_URL }}
          CROSSCHAIN: ${{ env.CROSSCHAIN }}

      - name: Remove builder cache
        if: always()                   # run this step always
        run: |
          docker system prune -f
