on:
  workflow_call:
  workflow_dispatch:


jobs:
  forkless-nodata:
    runs-on: [ redefi-03 ]
    timeout-minutes: 1380
    name: relay-forkless-nodata
    continue-on-error: true         #Do not stop testing of matrix runs failed.  As it decided during PR review - it required 50/50& Let's check it with false.

    steps:
      - name: Skip if pull request is in Draft
        if: github.event.pull_request.draft == true
        run: exit 1

      - name: Clean Workspace
        uses: AutoModality/action-clean@v1.1.0

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3.1.0
        with:
          ref: ${{ github.head_ref }}  #Checking out head commit

      # # Prepare SHA  
      # - name: Prepare SHA
      #   uses: ./.github/actions/prepare

      - name: Read .env file
        uses: xom9ikk/dotenv@v2

      - name: Pull polkadot image from official repository
        run: |
          docker pull parity/polkadot:v1.7.0

      - name: Prepare redefi-relay-runtime container
        uses: ./.github/actions/buildContainer
        id: redefi-relay-runtime
        with:
          container: redefi-relay-runtime
          tag: latest
          context: .docker
          dockerfile: Dockerfile-redefi-relay-runtime
          args: |
            --build-arg RUST_TOOLCHAIN=${{ env.RUST_TOOLCHAIN_RELAY_NODE }}
            --build-arg REDEFI_RELAY_RUNTIME=${{ env.REDEFI_RELAY_RUNTIME_VERSION }}          

      - name: Copy runtime wasm file to host
        run: |
          docker run -v $PWD:/infra --rm --entrypoint cp ${{ steps.redefi-relay-runtime.outputs.name }} /redefi/redefi_runtime.compact.compressed.wasm /infra/

      - name: Prepare redefi-relay-runtime container
        uses: ./.github/actions/buildContainer
        id: redefi-relay-runtime-latest
        with:
          container: redefi-relay-runtime
          tag: latest
          context: .docker
          dockerfile: Dockerfile-redefi-relay-runtime
          args: |
            --build-arg RUST_TOOLCHAIN=${{ env.RUST_TOOLCHAIN_RELAY_NODE }}
            --build-arg REDEFI_RELAY_RUNTIME=${{ env.REDEFI_RELAY_RUNTIME_LATEST_VERSION }}          

      - name: Copy runtime wasm file to host
        run: |
          docker run -v $PWD:/infra --rm --entrypoint cp ${{ steps.redefi-relay-runtime-latest.outputs.name }} /redefi/redefi_runtime.compact.compressed.wasm /infra/latest-redefi_runtime.compact.compressed.wasm

      - name: Extract wasms
        uses: ./.github/actions/extractDocker
        id: wasm
        with:
          image: ${{ steps.redefi-relay-runtime-latest.outputs.name }}
          directory: /redefi

      - name: Prepare redefi-relay mainnet container
        uses: ./.github/actions/buildContainer
        id: redefi-relay-mainnet
        with:
          container: redefi-relay
          tag: mainnet
          context: .docker
          dockerfile: Dockerfile-redefi-relay
          args: |
            --build-arg RUST_TOOLCHAIN=${{ env.RUST_TOOLCHAIN_RELAY_NODE }}
            --build-arg REDEFI_RELAY=${{ env.REDEFI_RELAY_MAINNET_VERSION }}     

      - name: Prepare redefi-parachain mainnet container
        uses: ./.github/actions/buildContainer
        id: redefi-parachain-mainnet
        with:
          container: redefi-parachain
          tag: mainnet
          context: .docker
          dockerfile: Dockerfile-redefi-parachain
          args: |
            --build-arg RUST_TOOLCHAIN=${{ env.RUST_TOOLCHAIN }}
            --build-arg REDEFI_PARACHAIN=${{ env.REDEFI_PARACHAIN_MAINNET_VERSION }}     

      - uses: actions/setup-node@v3.5.1
        with:
          node-version: 20

      - name: Install baedeker
        uses: UniqueNetwork/baedeker-action/setup@built
        with:
          version: v0.1.1

      - name: Setup library
        run: mkdir -p .baedeker/vendor/ && git clone https://github.com/UniqueNetwork/baedeker-library .baedeker/vendor/baedeker-library

      - name: Start network
        uses: UniqueNetwork/baedeker-action@built
        id: bdk
        with:
          jpath: |
            .baedeker/vendor
          tla-str: |
            relay_spec=westend-local
            fork_source=${{ env.relay_fork_source }}            
          inputs: |
            .baedeker/forkless-data.jsonnet
            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/polkadot':{dockerImage:'parity/polkadot:v1.7.0'}})
            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/redefi-relay':{dockerImage:'${{ steps.redefi-relay-mainnet.outputs.name }}'}})
            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/redefi-collator':{dockerImage:'${{ steps.redefi-parachain-mainnet.outputs.name }}'}})

      - name: Ensure network is alive before upgrade
        working-directory: ./tests
        if: success()
        run: |
          yarn
          ./scripts/wait_for_first_block.sh
        env:
          RPC_URL: ${{ env.REDEFI_RELAY_HTTP_URL }}

      - name: "Reconcile: runtime is upgraded"
        working-directory: ./tests
        run: |
          yarn
          ./scripts/wait_for_first_block.sh
          echo "Executing upgrade"
          yarn node --no-warnings=ExperimentalWarning --loader ts-node/esm util/authorizeEnactUpgrade.ts ${{ steps.wasm.outputs.dir }}/redefi_runtime.compact.compressed.wasm
        env:
          RPC_URL: ${{ env.REDEFI_RELAY_HTTP_URL }}

      - name: Ensure network is alive after upgrade
        working-directory: ./tests
        if: success()
        run: |
          yarn
          ./scripts/wait_for_first_block.sh
        env:
          RPC_URL: ${{ env.REDEFI_RELAY_HTTP_URL }}

      - name: Run tests after upgrade
        working-directory: ./tests
        if: success() || failure()    # run this step even if previous step failed
        run: |
          echo "Ready to start tests"
          yarn test
        env:
          RPC_URL: ${{ env.REDEFI_RELAY_HTTP_URL }}

      - name: Remove builder cache
        if: always()                   # run this step always
        run: |
          docker system prune -f
