name: test-reusable-vars

on:
  workflow_call:
    inputs:
      relay-node-version:
        type: string
        description: relay branch to build
        required: true
      relay-runtime-version:
        type: string
        description: relay runtime branch to build
        required: true
      parachain-version:
        type: string
        description: parachain branch to build
        required: true

jobs:
  test-reusable-vars:
    runs-on: [ self-hosted ]
    name: test-reusable-vars
    steps:
      - name: Clean Workspace
        if: always()
        uses: AutoModality/action-clean@v1.1.0

      - uses: actions/checkout@v4.1.7
        with:
          ref: ${{ github.head_ref }}  

      - name: relay node test reusable vars
        id: relay-node-test-reusable-vars
        run: |
          echo "Relay node version: ${{ inputs.relay-node-version }}"

      - name: checkout 'redefi-relay' 
        uses: actions/checkout@v4.1.7
        with:
          ref: ${{ inputs.relay-node-version }}  
          repository: 'ReDeFi-Blockchain/redefi-relay-node'
          path: 'redefi-relay-node'

      - name: relay runtime test reusable vars
        id: relay-runtime-test-reusable-vars
        run: |
          echo "Relay runtime version: ${{ inputs.relay-runtime-version }}"

      - name: paralachain test reusable vars
        id: parachain-test-reusable-vars
        run: |
          echo "Parachain version: ${{ inputs.parachain-version }}"
